name: GitHub Metrics Cool Card

on:
  schedule: 
    - cron: "0 */12 * * *"   # Updates every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AKASH-GHOSHT
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          # Extra cool plugins
          plugins_followup: yes
          plugins_languages: yes
          plugins_activity: yes
          plugins_achievements: yes
          plugins_lines: yes
          plugins_notable: yes
          plugins_stars: yes
          plugins_habits: yes
          plugins_calendar: yes
          plugins_topics: yes

          # Output file
          output: metrics.svg